language: go
go: tip
sudo: false
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
install: npm install -g typescript
script: $HOME/gopath/bin/goveralls -package ./apidts -service=travis-ci
